- name: Install and Run Nginx
  hosts: web
  become: Yes #rootuser
  tasks: 
  - name: Install
    ansible.builtin.dnf:
     name: nginx
     state: latest
  - name: Run
    ansible.builtin.service:
     name: nginx
     state: started
     enabled: Yes
