- name: variables
  hosts: localhost
  vars: 
   country: "India"
   city: "Seattle"
   age: "5"
  tasks: 
   - name: Declaring Variables
     ansible.builtin.debug:
      msg: "I am from {{country}}, i live in {{city}}, we have a {{age}} year old daughter"