- name: variables
  hosts: localhost
  vars: #playlevel varaibles
   country: "India"
   city: "Seattle"
   age: "5"
  tasks: 
  - name: Print override info
    vars: #tasklevel variables
       country: "Unitedstates"
    ansible.builtin.debug:
       msg: "I am from {{country}}, i live in {{city}}, we have a {{age}} year old daughter"

  - name: Print information
    ansible.builtin.debug:
       msg: "I am from {{country}}, i live in {{city}}, we have a {{age}} year old daughter"
        
