- name: variables from inventory file
  hosts: localhost
  vars:
   religion: "Hindu"
  tasks: 
   - name: Declaring Variables
     ansible.builtin.debug:
      msg: "I am from {{country}}, i live in {{city}}, we have a {{age}} year old daughter,Religion is: {{religion}}"