- name: variables from inventory
  hosts: localhost
  tasks: 
   - name: Declaring Variables
     ansible.builtin.debug:
      msg: "I am from {{country}}, i live in {{city}}, we have a {{age}} year old daughter"