- name: conditions
  hosts: web
  become: yes
  tasks: 
    - name: check user exists or not
      ansible.builtin.command: id command

    - name: print user information
      ansible.builtin.debug:
       msg: "Hello"