- name: conditions
  hosts: web
  become: yes
  tasks:
    - name: check user exists or not
      ansible.builtin.command: id expense
      register: USER
      ignore_errors: true

    - name: Checking the userinfo
      ansible.builtin.debug:
        msg: "check the user info: {{USER}}"

    - name: create user
      ansible.built.command: useradd expense
      when: USER.rc != 0 #condition

    - name: print user information
      ansible.builtin.debug:
        msg: Hello
