- name: Default variable
  hosts: localhost
  tasks:
   - name: Declaring default variables
     ansible.builtin.debug:
      msg: "Hello  {{course | default('ansible')}}"

- name: Uppercase
  hosts: localhost
  vars:
    greetings: "good morning" 
  tasks:
   - name: convert into uppercase
     ansible.builtin.debug:
      msg: "{{greetings | upper}}"

- name: Lowercase
  hosts: localhost
  vars:
    greetings: "GOOD MORNING" 
  tasks:
   - name: convert into lowercase
     ansible.builtin.debug:
      msg: "{{greetings | lower}}"


- name: removing duplicates
  hosts: localhost
  vars:
   numbers: [1,1,1,3,4,5,6,6,7,8,8]
  tasks:
    - name: Remove Duplicates
      ansible.builtin.debug:
        msg: "{{ numbers | unique}}"

- name: finding Min and max
  hosts: localhost
  vars:
    age: [6,33,39,50,78,67]
  tasks:
   - name: Min and max ages
     ansible.builtin.debug:
      msg: "min age is: {{age | min}}, max age  is: {{age | max}}"
  
- name: converting dictionary to lists
  hosts: localhost
  vars:
   my_dict:
    course: ansible
    Trainer: Sivakumar
    Duration: 120hrs
  tasks:
    - name: before converting to list
      ansible.builtin.debug:
       msg: "before convert: {{ my_dict }}"
    - name: after converting to list
      ansible.builtin.debug:
       msg: "after converting: {{ my_dict | dict2items }}
