- name: Default variable
  hosts: localhost
  tasks:
   - name: Declaring default variables
     ansible.builtin.debug:
      msg: "Hello  {{course | default('ansible')}}"

- name: Uppercase
  hosts: localhost
  vars:
    greetings: "good morning" 
  tasks:
   - name: convert into uppercase
     ansible.builtin.debug:
      msg: "{{greetings | upper}}"

- name: Lowercase
  hosts: localhost
  vars:
    greetings: "good morning" 
  tasks:
   - name: convert into lowercase
     ansible.builtin.debug:
      msg: "{{greetings | lower}}"