- name: install packages
  host: localhost
  become: yes
  tasks:
  - name: install packages
    ansible.builtin.dnf:
     name: "{{item}}"
     state: latest
    loop:
     - ansible
     - nginx
     - postfix